### ISSUE TITLE
ssl.SSLError: [SSL: TLSV1_UNRECOGNIZED_NAME]

### ISSUE THREAD

**Issue by oTree-org** [gwik/geventhttpclient#140]
Hello, I am unable to make requests to the Heroku API. Here is my code:

```
import geventhttpclient

client = geventhttpclient.HTTPClient.from_url('https://api.heroku.com')
data = client.get(
    '/schema',
    headers={
        'Accept': 'application/vnd.heroku+json; version=3',
        'Content-Type': 'application/json',
    },
)
print(data)
```

I get:

```
Traceback (most recent call last):
  File "C:\path\venv39\lib\site-packages\geventhttpclient\connectionpool.py", line 163, in get_socket
    return self._socket_queue.get(block=False)
  File "src\\gevent\\queue.py", line 335, in gevent._gevent_cqueue.Queue.get
  File "src\\gevent\\queue.py", line 350, in gevent._gevent_cqueue.Queue.get
  File "src\\gevent\\queue.py", line 319, in gevent._gevent_cqueue.Queue._Queue__get_or_peek
    '''Return the approximate size of the queue (not reliable!).'''
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\path\public.py", line 5, in <module>
    data = client.get(
  File "C:\path\venv39\lib\site-packages\geventhttpclient\client.py", line 266, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "C:\path\venv39\lib\site-packages\geventhttpclient\client.py", line 226, in request
    sock = self._connection_pool.get_socket()
  File "C:\path\venv39\lib\site-packages\geventhttpclient\connectionpool.py", line 166, in get_socket
    return self._create_socket()
  File "C:\path\venv39\lib\site-packages\geventhttpclient\connectionpool.py", line 127, in _create_socket
    raise first_error
  File "C:\path\venv39\lib\site-packages\geventhttpclient\connectionpool.py", line 114, in _create_socket
    sock = self._connect_socket(sock, sock_info[-1])
  File "C:\path\venv39\lib\site-packages\geventhttpclient\connectionpool.py", line 248, in _connect_socket
    return gevent.ssl.wrap_socket(sock, **ssl_options)
  File "C:\path\venv39\lib\site-packages\gevent\_ssl3.py", line 797, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "C:\path\venv39\lib\site-packages\gevent\_ssl3.py", line 312, in __init__
    raise x
  File "C:\path\venv39\lib\site-packages\gevent\_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "C:\path\venv39\lib\site-packages\gevent\_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1122)
```

However, it works fine when I make the request using cURL, requests, or grequests:

```
import grequests

task = grequests.get(
    'https://api.heroku.com/schema',
    headers={
        'Accept': 'application/vnd.heroku+json; version=3',
        'Content-Type': 'application/json',
    },
)
[resp] = grequests.map([task])
print(resp.json())
```

Strangely, the geventhttpclient code seemed to work fine before today. I tested on Windows and Linux, with gevent 1.4.0 and 21.1.2, and python 3.7 and 3.9.

Thank you for your time.

**Comment by oTree-org** [comment]
It may be related to Heroku now requiring SNI: https://devcenter.heroku.com/changelog-items/2077

**Comment by oTree-org** [comment]
I fixed it by passing `ssl_context_factory=gevent.ssl.create_default_context` to the HTTPClient constructor. Also may need to pass `ssl_options={'server_hostname': 'api.heroku.com'},`.
