### ISSUE TITLE
is pypy supported - error on import

### ISSUE THREAD

**Issue by davidmontgom** [gwik/geventhttpclient#59]
Here is how I install PYPY:
   wget https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.0-linux64.tar.bz2
    tar jxf pypy-2.5.0-linux64.tar.bz2
    mv pypy-2.5.0-linux64 /opt/pypy
    cd /opt/pypy/site-packages/
    wget http://nightly.ziade.org/distribute_setup.py
    /opt/pypy/bin/pypy distribute_setup.py
    ln -s /opt/pypy/bin/pypy /usr/bin/pypy

   /opt/pypy/bin/easy_install greenlet
   /opt/pypy/bin/easy_install git+git://github.com/surfly/gevent.git#egg=gevent
   /opt/pypy/bin/easy_install geventhttpclient

This is the error I get on ubuntu 14.04

Python 2.7.8 (10f1b29a2bd2, Feb 02 2015, 21:22:43)
[PyPy 2.5.0 with GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > > from geventhttpclient import HTTPClient
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > >   File "/opt/pypy/site-packages/geventhttpclient-1.1.0-py2.7-linux-x86_64.egg/geventhttpclient/**init**.py", line 5, in <module>
> > > >     from geventhttpclient.client import HTTPClient
> > > >   File "/opt/pypy/site-packages/geventhttpclient-1.1.0-py2.7-linux-x86_64.egg/geventhttpclient/client.py", line 3, in <module>
> > > >     from geventhttpclient.response import HTTPSocketPoolResponse
> > > >   File "/opt/pypy/site-packages/geventhttpclient-1.1.0-py2.7-linux-x86_64.egg/geventhttpclient/response.py", line 2, in <module>
> > > >     from geventhttpclient._parser import HTTPResponseParser, HTTPParseError #@UnresolvedImport
> > > >   File "/opt/pypy/site-packages/geventhttpclient-1.1.0-py2.7-linux-x86_64.egg/geventhttpclient/_parser.py", line 7, in <module>
> > > >     __bootstrap__()
> > > >   File "/opt/pypy/site-packages/geventhttpclient-1.1.0-py2.7-linux-x86_64.egg/geventhttpclient/_parser.py", line 6, in __bootstrap__
> > > >     imp.load_dynamic(**name**,**file**)
> > > > ImportError: unable to load extension module '/opt/pypy/site-packages/geventhttpclient-1.1.0-py2.7-linux-x86_64.egg/geventhttpclient/_parser.pypy-25.so': /opt/pypy/site-packages/geventhttpclient-1.1.0-py2.7-linux-x86_64.egg/geventhttpclient/_parser.pypy-25.so: undefined symbol: PyByteArray_FromStringAndSize

**Comment by gwik** [comment]
There is a PR here https://github.com/gwik/geventhttpclient/pull/30
Maybe you can try it and report back.

**Comment by cyberw** [comment]
Closing due to lack of activity
